const HEADER_URL = {
  CONTRACT_SERVICE: process.env.REACT_APP_CONTRACT_SERVICE,
  LOGIN_SERVICE: process.env.REACT_APP_LOGIN_SERVICE,
  BUSINESS_PLAN_SERVICE: process.env.REACT_APP_BUSINESS_PLAN_SERVICE,
  CORE_SERVICE: process.env.REACT_APP_CORE_SERVICE,
  CROP_SERVICE: process.env.REACT_APP_CROP_SERVICE,
  WORK_ORDER_SERVICE: process.env.REACT_APP_WORK_ORDER_SERVICE,
  LAND_SERVICE: process.env.REACT_APP_LAND_SERVICE,
  NATURAL_ASPECT_SERVICE: process.env.REACT_APP_NATURAL_ASPECT_SERVICE,
  BUSINESS_PARTNER_SERVICE: process.env.REACT_APP_BUSINESS_PARTNER_SERVICE,
  HUMAN_RESOURCE_SERVICE: process.env.REACT_APP_HUMAN_RESOURCE_SERVICE,
  SEASON_SERVICE: process.env.REACT_APP_SEASON_SERVICE,
};

const API_URL = {
  // LOGIN SERVICE URL
  GET_LOGIN_KEY: `${HEADER_URL.LOGIN_SERVICE}Auth/LoginGetKey`,
  POST_LOGIN: `${HEADER_URL.LOGIN_SERVICE}Auth/Login`,
  POST_CHANGE_PASSWORD: `${HEADER_URL.LOGIN_SERVICE}Auth/ChangePassword`,

  // BUSINESS PLAN HEADER URL
  GET_BUSINESS_PLAN_HEADER_LIST: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanHeader/GetBusinessPlanHeaderList`,
  POST_BUSINESS_PLAN_HEADER_SINGLE: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanHeader/GetBusinessPlanHeaderById`,
  POST_BUSINESS_PLAN_HEADER_CREATE: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanHeader/CreateBusinessPlanHeader`,
  POST_BUSINESS_PLAN_HEADER_UPDATE: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanHeader/UpdateBusinessPlanHeader`,

  // BUSINESS PLAN LINES URL
  GET_BUSINESS_PLAN_LINE_LIST: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanLines/GetPPPlanLinesList`,
  GET_BUSINESS_PLAN_LINE_WITH_QUANTITY_LIST: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanLines/GetBusinessPlanLinesListWithQty`,

  GET_STATES_FROM_BUSSINESS_PLAN_LINE_LIST: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanLines/GetStatesListByBusinessPLanLinesID`,
  POST_CREATE_PLAN_LINES: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanLines/CreatePlanLines`,
  POST_CREATE_PLAN_LINE: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanLines/CreateBusinessPlanLine`,
  POST_UPDATE_BUSSINESS_PLAN_LINE_COST: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanLines/UpdateBusinessPlanLineCosting`,

  // BUSINESS PLAN CYCLE URL
  GET_BUSINESS_PLAN_CYCLE_LIST: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanCycle/GetPpPlanLinesCycleList`,
  POST_BUSINESS_CREATE_PLAN_CYCLE: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanCycle/CreatePlanCycle`,
  POST_BUSINESS_CREATE_PLAN_CYCLES: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanCycle/CreatePlanCycle`,
  GET_USED_LAND_FROM_BUSINESS_PLAN_CYCLES: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanCycle/GetUsedLandinBusinessPlan`,
  POST_UPDATE_BUSINESS_PLAN_CYCLE_QUANTITY: `${HEADER_URL.BUSINESS_PLAN_SERVICE}BusinessPlanCycle/UpdateBPCycleQty`,

  // LAND REGISTERATION SERVICE URL
  GET_LAND_REGISTERATION_FROM_COUNTRY_LIST: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/GetAllLandRegistration`,
  GET_LAND_REGISTERATION_SINGLE: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/GetAllLandRegistrationById`,
  GET_LAND_REGISTERATION_FROM_CZSL: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/GetLandRegistration`,
  POST_LAND_REGISTERATION: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/CreateLandRegistration`,
  GET_SUM_OF_LAND_AREA: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/GetSumofLandArea`,
  POST_FARMER_DUTIES: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/CreateFarmerDuties`,
  POST_SUPERVISOR_DUTIES: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/CreateSupervisorDuties`,

  // LAND BUSINESS PLAN URL ( PPLAND )
  GET_BUSINESS_PLAN_LAND_LIST: `${HEADER_URL.LAND_SERVICE}PPPlanLand/GetAllPPPlanLand`,
  POST_BUSINESS_PLAN_LAND: `${HEADER_URL.LAND_SERVICE}PPPlanLand/CreatePPPlanLand`,
  GET_PLAN_LAND_DETAIL: `${HEADER_URL.LAND_SERVICE}PPPlanLand/GetPPPlanLandDetails`,

  // LAND SERVICE URL ( PPLAND )
  GET_FARMER_DUTIES_LIST: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/GetFarmerDuties`,
  GET_SUPERVISOR_DUTIES_LIST: `${HEADER_URL.LAND_SERVICE}LnLandRegisterations/GetSupervisorDuties`,

  // CONTRACT URL
  GET_LAND_CONTRACT_LIST: `${HEADER_URL.CONTRACT_SERVICE}BusinessContract/GetContractList`,
  GET_CONTRACT_LINE_LIST: `${HEADER_URL.CONTRACT_SERVICE}BusinessContract/GetContractLineListByContractId`,

  // CROP SERVICE URL
  GET_CROP_CYCLE_AREA_LIST: `${HEADER_URL.CROP_SERVICE}CropCycle/GetCropCycleAreaList`,
  GET_CROP_VARIETY_LIST: `${HEADER_URL.CROP_SERVICE}CropClassification/GetCropVariety`,
  GET_CROP_CLASSIFICATION_LIST: `${HEADER_URL.CROP_SERVICE}CropClassification/GetCropClassification`,
  GET_CROP_SUB_CLASSIFICATION_LIST: `${HEADER_URL.CROP_SERVICE}CropClassification/GetCropSubClassification`,
  GET_CROP_CLASS_AND_SUBCLASS_LIST: `${HEADER_URL.CROP_SERVICE}CropClassification/GetCropByClassAndSubClass`,
  GET_CROP_LIST: `${HEADER_URL.CROP_SERVICE}CropClassification/GetCropList`,
  GET_CROP_STANDARD_YEILD_LIST: `${HEADER_URL.CROP_SERVICE}CropStandardYield/GetCropStdYield`,
  GET_CROP_CYCLE_LIST: `${HEADER_URL.CROP_SERVICE}CropCycle/GetCropCycleList`,
  GET_CROP_ACTIVITY_LIST: `${HEADER_URL.CROP_SERVICE}CropActivity/GetAllCrActivityList`,
  GET_CROP_LIST_BY_COUNTRY_ID: `${HEADER_URL.CROP_SERVICE}CropClassification/GetCropListByCountry`,

  CREATE_CROP_CYCLE: `${HEADER_URL.CROP_SERVICE}CropCycle/CreateCropCycle`,
  CREATE_CROP_CYCLE_AREA: `${HEADER_URL.CROP_SERVICE}CropCycle/CreateCropCycleArea`,
  GET_CROP_ACTIVITY_FROM_COUNTRY_LIST: `${HEADER_URL.CROP_SERVICE}CropActivity/GetCropActivityListByCountryId`,
  CREATE_CROP_STD_YIELD: `${HEADER_URL.CROP_SERVICE}CropStandardYield/CreateCropStdYield`,
  CREATE_CROP_CLASSIFICATION: `${HEADER_URL.CROP_SERVICE}CropClassification/CreateClassification`,
  CREATE_CROP_SUB_CLASSIFICATION: `${HEADER_URL.CROP_SERVICE}CropClassification/CreateCropSubClassification`,
  CREATE_CROP: `${HEADER_URL.CROP_SERVICE}CropClassification/CreateCrop`,
  CREATE_CROP_VARIETY: `${HEADER_URL.CROP_SERVICE}CropClassification/CreateCropVariety`,
  CREATE_ACTIVITY: `${HEADER_URL.CROP_SERVICE}CropActivity/CreateActivityMaster`,
  CREATE_CROP_MILESTONE: `${HEADER_URL.CROP_SERVICE}CropActivity/CreateCropMileStone`,
  GET_CROP_MILESTONE: `${HEADER_URL.CROP_SERVICE}CropActivity/GetCropMileStoneList`,
  CREATE_CROP_ACTIVITY: `${HEADER_URL.CROP_SERVICE}CropActivity/CreateCropActivity`,
  GET_YIELD_FROM_CROP_VARIETY_STATE: `${HEADER_URL.CROP_SERVICE}CropClassification/GetYieldByCropVarietyState`,

  // CORE SERVICE URL
  GET_FINANCIAL_YEAR_LIST: `${HEADER_URL.CORE_SERVICE}CoreEngine/GetDDFinYearList`,
  GET_FINANCIAL_YEAR_DATES: `${HEADER_URL.CORE_SERVICE}CoreEngine/GetDDFinYearFromToDate`,
  GET_COUNTRIES_LIST: `${HEADER_URL.CORE_SERVICE}CoreEngine/CountriesList`,
  GET_ZONE_LIST: `${HEADER_URL.CORE_SERVICE}CoreEngine/GetZonesByCountryId`,
  GET_STATES: `${HEADER_URL.CORE_SERVICE}CoreEngine/GetStateByCountryZoneId`,
  GET_UOM_LIST: `${HEADER_URL.CORE_SERVICE}CoreEngine/GetDdUomList`,
  POST_UOM: `${HEADER_URL.CORE_SERVICE}CoreEngine/CreateDDUom`,
  POST_FINANCIAL_YEAR: `${HEADER_URL.CORE_SERVICE}CoreEngine/CreateDDFinYear`,
  GET_USER_LIST: `${HEADER_URL.CORE_SERVICE}CoreEngine/GetDDUserList`,
  POST_USER: `${HEADER_URL.CORE_SERVICE}CoreEngine/CreateDDUser`,
  RESET_PASSWORD: `${HEADER_URL.CORE_SERVICE}CoreEngine/ResetPassword`,

  // WORK ORDER SERVICE URL
  GET_WORK_ORDER_LIST: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/GetAllWoWorkOrder`,
  GET_WORK_ORDER_SINGLE: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/GetWoWorkOrderDetails`,
  GET_UTILIZED_WORK_ORDER_QUANTITY: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/GetUtilizedWorkOrderQty`,
  POST_WORK_ORDER_CREATE: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/CreateWoWorkOrder`,
  GET_WORK_ORDER_OBSERVATION_LIST: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/GetWorkOrderActivityObservations`,
  GET_WORK_ORDER_ACTIVITIES_FROM_USER_TYPE_LIST: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/GetWOActivityResponseList`,
  POST_WORK_ORDER_ACTIVITIES_SYNC: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/CreateWorkOrderActivities`,
  POST_WORK_ORDER_FARMER_ACTIVITY_CREATE: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/CreateFarmerActivity`,
  POST_WORK_ORDER_SUPERVISOR_ACTIVITY_CREATE: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/CreateSuperVisorActivity`,
  GET_WO_DOCUMENT_STATUS: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/GetWODocumentStatus`,
  UPDATE_WO_STATUS: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrder/UpdateWOStatus`,

  // WORK ORDER ACTIVITY URL
  GET_WORK_ORDER_ACTIVITY_LIST: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrderLine/GetWorkOrderActivityListById`,
  GET_WORK_ORDER_LINE: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrderLine/GetAllWoWorkOrderLine`,
  POST_WORK_ORDER_LINE: `${HEADER_URL.WORK_ORDER_SERVICE}WorkOrderLine/CreateWoWorkOrderLines`,

  // NATURAL ASPECT SERVICE URL
  GET_DISEASE_LIST: `${HEADER_URL.NATURAL_ASPECT_SERVICE}NaturalAspects/DiseasesList`,
  CREATE_DISEASE: `${HEADER_URL.NATURAL_ASPECT_SERVICE}NaturalAspects/CreateDisease`,
  GET_INSECT_LIST: `${HEADER_URL.NATURAL_ASPECT_SERVICE}NaturalAspects/InsectsList`,
  CREATE_INSECT: `${HEADER_URL.NATURAL_ASPECT_SERVICE}NaturalAspects/CreateInsect`,

  // BUSINESS PARTNER SERVICE URL
  GET_BUSINESS_PARTNER_LIST: `${HEADER_URL.BUSINESS_PARTNER_SERVICE}BusinessPartner/GetAllBPartnerList`,
  CREATE_FARMER: `${HEADER_URL.BUSINESS_PARTNER_SERVICE}BusinessPartner/CreateFarmer`,

  // HR SERVICE URL
  GET_HR_MEMBER_LIST: `${HEADER_URL.HUMAN_RESOURCE_SERVICE}HR/GetAllHRMemberList`,
  CREATE_SUPERVISOR: `${HEADER_URL.HUMAN_RESOURCE_SERVICE}HR/CreateSupervisor`,

  // SEASON SERVICE URL
  GET_SEASON_LIST: `${HEADER_URL.SEASON_SERVICE}Season/GetSeasonsList`,
};

export default API_URL;
